name: Feature Request / Feature 请求
description: "Make a suggestion for this project. 为这个项目提出一个建议。"
title: "[Feature request]: "
labels: ["enhancement"]
body:
  - type: input
    id: problem
    attributes:
      label: Related Problem / 相关问题
      description: "Describe clearly and concisely what the problem is 清楚而简洁地描述问题是什么"
      placeholder: "When I want to ......, the software cannot ...... 当我想要......时，软件不能......"
    validations:
      required: true
  - type: input
    id: way-to-solve
    attributes:
      label: Describe the solution you want / 描述你希望的解决方案
      description: "What do you want to happen 你希望发生什么"
    validations:
      required: true
  - type: input
    id: instead
    attributes:
      label: Describe the alternatives you are considering / 描述你所考虑的替代方案
    validations:
      required: false
  - type: checkboxes
    id: "issues"
    attributes:
      label: "I confirm that I have checked the history issues / 我确认已查询历史 issues"
      description: "Otherwise, please raise the issue after check 否则请查询后提出"
      options:
        - label: Yes / 是
          required: true
