name: Bug Report / Bug 报告
description: Please upgrade to the latest version before asking a question, and also check by searching to see if someone else has asked the same question. 在提出问题前请先升级到最新版本，同时也请通过搜索确认是否有人提出过相同问题。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: "expectation"
    attributes:
      label: "Expectation / 预期情况"
      description: "Describe what you think should happen 描述你认为应该发生什么"
    validations:
      required: true
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "Actual Situation / 实际情况"
      description: "Describe what actually happened 描述实际发生了什么"
    validations:
      required: true
  - type: textarea
    id: "reproduction-method"
    attributes:
      label: "Reproduction Method / 复现方法"
      description: "The actions/commands entered before the bug appeared, with important/private information omitted BUG 出现前执行的操作 / 输入的命令，注意隐去重要/隐私信息"
      placeholder: Mark it with a serial number / 标序号
    validations:
      required: true
  - type: textarea
    id: "log"
    attributes:
      label: "Log / 日志信息"
      description: "Enter the console output error message, taking care to obscure important/private information 控制台输出错误信息，注意隐去重要/隐私信息"
      placeholder: Paste the following after the colon at the beginning and end of the log 在日志开始和结束位置粘贴冒号后的内容：```
    validations:
      required: false
  - type: textarea
    id: "more"
    attributes:
      label: "More information / 额外信息"
      description: "Optional 可选"
    validations:
      required: false
  - type: checkboxes
    id: "latest-version"
    attributes:
      label: "I confirm that I have updated to the latest version / 我确认已更新至最新版本"
      description: "Otherwise, please update and try 否则请更新后尝试"
      options:
        - label: Yes / 是
          required: true
  - type: checkboxes
    id: "issues"
    attributes:
      label: "I confirm that I have checked the history issues / 我确认已查询历史 issues"
      description: "Otherwise, please raise the issue after check 否则请查询后提出"
      options:
        - label: Yes / 是
          required: true
