name: "Build resolvconf"

on:
  workflow_dispatch:

jobs:
  Building:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest
    steps:
    - name: Build resolvconf v3.12.0
      run: |
        mkdir -p /opt/release/
        wget https://github.com/rsmarples/openresolv/archive/openresolv-3.12.0.tar.gz
        tar xzvf openresolv-3.12.0.tar.gz
        cd openresolv-openresolv-3.12.0
        ./configure
        make
        sudo make install
        sudo cp ./resolvconf /opt/release/

    - name: Release binaries 
      uses: softprops/action-gh-release@v1
      with:
          tag_name: resolvconf
          files: /opt/release/resolvconf
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
