name: Cross compile WireProxy

on:
  workflow_dispatch:
#  push:
#    tags:
#      - "v*"

jobs:
  WireProxy:

    name: Cross compile WireProxy

    runs-on: ubuntu-20.04

    env:
      workdir: ./WireProxy
      VERSION: 1.0.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Git clone WireProxy
        run: |
          git clone https://github.com/octeep/wireproxy.git ${{ env.workdir }}
          cp ./.github/wireproxy-releaser.yml ${{ env.workdir }}/.goreleaser.yml
      - name: Set up GoReleaser
        uses: actions/setup-go@v4.0.1
        with:
          go-version: "1.18"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.3.0
        with:
          distribution: goreleaser
          workdir: ${{ env.workdir }}
          version: latest
          args: release --clean
          
      - name: Release binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: WireProxy_v${{ env.VERSION }}
          files: ${{ env.workdir }}/dist/*.tar.gz
